// @draft: generated by bughunter scaffolder — review before enabling.
// Target: beautycita_web/lib/providers/admin_applications_provider.dart
//
// This scaffold compiles but only contains stub assertions. Fill in real
// expectations before treating it as a regression net. When you're done,
// remove the @draft marker.

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:beautycita_web/providers/admin_applications_provider.dart';

void main() {
  group('ApplicationBusiness', () {
    late ProviderContainer container;

    setUp(() {
      container = ProviderContainer();
    });

    tearDown(() {
      container.dispose();
    });

    test('initial state is sane', () {
      // TODO: assert the initial state of the provider under test.
      expect(container, isNotNull);
    });

    test('withVerification mutates state as expected', () async {
      // TODO: arrange + act + assert for withVerification.
    });
    test('setApplicationsSearch mutates state as expected', () async {
      // TODO: arrange + act + assert for setApplicationsSearch.
    });
    test('rejectApplication mutates state as expected', () async {
      // TODO: arrange + act + assert for rejectApplication.
    });
    test('approveLicense mutates state as expected', () async {
      // TODO: arrange + act + assert for approveLicense.
    });
    test('rejectLicense mutates state as expected', () async {
      // TODO: arrange + act + assert for rejectLicense.
    });
  });
}
