// @draft: generated by bughunter scaffolder — review before enabling.
// Target: beautycita_app/lib/providers/chat_provider.dart
//
// This scaffold compiles but only contains stub assertions. Fill in real
// expectations before treating it as a regression net. When you're done,
// remove the @draft marker.

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';


void main() {
  group('SendMessageNotifier', () {
    late ProviderContainer container;

    setUp(() {
      container = ProviderContainer();
    });

    tearDown(() {
      container.dispose();
    });

    test('initial state is sane', () {
      // TODO: assert the initial state of the provider under test.
      expect(container, isNotNull);
    });

    test('send mutates state as expected', () async {
      // TODO: arrange + act + assert for send.
    });
  });
}
